-- Tablas principales para la app completa
CREATE TABLE IF NOT EXISTS wells (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, location TEXT, zona TEXT);
CREATE TABLE IF NOT EXISTS rigs (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT UNIQUE);
CREATE TABLE IF NOT EXISTS tanks (id INTEGER PRIMARY KEY AUTOINCREMENT, well_id INTEGER, name TEXT, capacity REAL, volume_unit TEXT DEFAULT 'm3', current_volume REAL DEFAULT 0, FOREIGN KEY(well_id) REFERENCES wells(id));
CREATE TABLE IF NOT EXISTS products (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, category TEXT, unit TEXT DEFAULT 'kg', density REAL, bag_weight_kg REAL, cost_per_unit REAL, stock_min_kg REAL);
CREATE TABLE IF NOT EXISTS fluid_properties (id INTEGER PRIMARY KEY AUTOINCREMENT, well_id INTEGER, ts TEXT, rig TEXT, density REAL, pv REAL, yp REAL, gels_10s REAL, gels_10m REAL, filtrate_ml REAL, sand_pct REAL, ph REAL, chlorides_mgL REAL, calcium_mgL REAL, potassium_mgL REAL, lgs_pct REAL, solids_pct REAL, temperature_C REAL, remarks TEXT, unit_system TEXT DEFAULT 'metric', FOREIGN KEY(well_id) REFERENCES wells(id));
CREATE TABLE IF NOT EXISTS consumptions (id INTEGER PRIMARY KEY AUTOINCREMENT, well_id INTEGER, ts TEXT, rig TEXT, product_id INTEGER, qty REAL, qty_unit TEXT, tank_id INTEGER, target_volume REAL, volume_unit TEXT DEFAULT 'm3', conc_value REAL, conc_unit TEXT DEFAULT 'kg/m3', cost_value REAL, notes TEXT, FOREIGN KEY(well_id) REFERENCES wells(id), FOREIGN KEY(product_id) REFERENCES products(id), FOREIGN KEY(tank_id) REFERENCES tanks(id));
CREATE TABLE IF NOT EXISTS volumes_log (id INTEGER PRIMARY KEY AUTOINCREMENT, well_id INTEGER, ts TEXT, rig TEXT, tank_id INTEGER, action TEXT, volume REAL, unit TEXT DEFAULT 'm3', notes TEXT, FOREIGN KEY(well_id) REFERENCES wells(id), FOREIGN KEY(tank_id) REFERENCES tanks(id));
CREATE TABLE IF NOT EXISTS inventory_movements (id INTEGER PRIMARY KEY AUTOINCREMENT, ts TEXT, rig TEXT, well_id INTEGER, product_id INTEGER, movement_type TEXT, qty_kg REAL, cost_value REAL, notes TEXT, doc_ref TEXT, FOREIGN KEY(well_id) REFERENCES wells(id), FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE IF NOT EXISTS prepared_solutions (id INTEGER PRIMARY KEY AUTOINCREMENT, well_id INTEGER, ts TEXT, rig TEXT, product_id INTEGER, target_conc_kgm3 REAL, volume_m3 REAL, required_qty_kg REAL, tank_id INTEGER, cost_value REAL, notes TEXT, FOREIGN KEY(well_id) REFERENCES wells(id), FOREIGN KEY(product_id) REFERENCES products(id), FOREIGN KEY(tank_id) REFERENCES tanks(id));
